### ISSUE TITLE
Fix items following you when you loop around screen.

### ISSUE THREAD

**Issue by Trikzon** [devlup-fsu/party-pirates#14]
![image](https://github.com/devlup-fsu/party-pirates/assets/29845000/c2dce88c-5ca3-4e72-8ce9-8c8cf0962787)

**Comment by BillyJoelsNightmareExplosion** [comment]
@Trikzon here's my fix:
![modcoord](https://github.com/devlup-fsu/party-pirates/assets/84729196/717f0789-f4ae-4046-9287-bf82ac159ff8)
